package drools.cookbook.chapter01

import java.util.Date
import java.util.List
import drools.cookbook.chapter01.Server
import drools.cookbook.chapter01.ServerEvent
import drools.cookbook.chapter01.ServerStatus

global drools.cookbook.chapter01.ServerAlert alerts

rule "Server status"
dialect "mvel"
timer (cron:0/5 * * * * ?)
when
	$server : Server(online==false)
then
	Date currentTime = new Date();
	System.out.println("WARNING: Server \"" + $server.name + "\" is offline at " + currentTime);
	alerts.addEvent(new ServerEvent($server, currentTime, ServerStatus.OFFLINE));
end