package drools.cookbook.chapter01

import java.util.Date
import java.util.List

global drools.cookbook.chapter01.ServerAlert alerts

rule "Server status"
dialect "mvel"
timer (cron:0/5 * * * * ?)
when
	$server : Server(online==false)
then
	System.out.println("WARNING: Server \"" + $server.name + "\" is offline at " + $server.lastTimeOnline);
	alerts.addEvent(new ServerEvent($server, $server.lastTimeOnline, ServerStatus.OFFLINE));
end