package drools.cookbook.chapter01

import java.util.Date
import java.util.List
import drools.cookbook.chapter01.Server
import drools.cookbook.chapter01.Virtualization
import drools.cookbook.chapter01.VirtualizationRequest

rule "New virtualization request"
calendars "only-weekdays"
dialect "mvel"
when
	$request : VirtualizationRequest($serverName : serverName)
	$server : Server(name==$serverName)
then
	System.out.println("New virtualization added on server " + $serverName);
	$server.getVirtualizations().add($request.getVirtualization());
	$request.setSuccessful(true);
	retract($request);
end