package drools.cookbook.chapter01

import java.util.Date
import java.util.List

rule "New virtualization request"
calendars "only-weekdays"
when
	$request : VirtualizationRequest($serverName : serverName)
	$server : Server(name==$serverName)
then
	System.out.println("New virtualization added on server " + $serverName);
	$server.getVirtualizations().add($request.getVirtualization());
	$request.setSuccessful(true);
	retract($request);
end